apiVersion: v1
kind: ServiceAccount
metadata:
  name: sorry-gke
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sorry-gke
  namespace: kube-system
rules:
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/status"]
    verbs: ["list", "get", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sorry-gke
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sorry-gke
subjects:
  - kind: ServiceAccount
    name: sorry-gke
    namespace: kube-system
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: sorry-gke
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: sorry-gke
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sorry-gke
  namespace: kube-system
  labels:
    app: sorry-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorry-gke
  template:
    metadata:
      labels:
        app: sorry-gke
    spec:
      serviceAccountName: sorry-gke
      containers:
      - name: sorry-gke
        image: guyguy333/sorry-gke
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 25m
            memory: 200Mi
          requests:
            cpu: 25m
            memory: 50Mi

